# Generated by Django 3.2.6 on 2021-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locos',
            fields=[
                ('loco_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('loco_type', models.CharField(default=None, max_length=64)),
                ('model_name', models.CharField(default=None, max_length=64)),
                ('power_type', models.CharField(default=None, max_length=64)),
                ('length', models.CharField(default=None, max_length=64)),
                ('height', models.CharField(default=None, max_length=64)),
                ('maximum_speed', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('axles', models.IntegerField()),
                ('location', models.CharField(default=None, max_length=64)),
                ('image', models.URLField(default=None)),
            ],
        ),
    ]
