# Generated by Django 3.2.6 on 2021-10-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0002_freight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.AutoField(default=None, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='freight',
            name='image',
            field=models.URLField(default=None),
        ),
    ]
