# Generated by Django 3.2.6 on 2021-10-19 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0003_auto_20211019_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='length',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='freight',
            name='height',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='freight',
            name='length',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='freight',
            name='width',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
