# Generated by Django 3.2.6 on 2021-10-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0004_auto_20211019_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='capacity',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='passenger',
            name='height',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='image',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='passenger',
            name='width',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
