# Generated by Django 3.2.6 on 2021-10-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0005_auto_20211019_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='freight',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
