# Generated by Django 3.2.6 on 2021-10-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locos',
            old_name='model_type',
            new_name='loco_type',
        ),
        migrations.AddField(
            model_name='locos',
            name='model_name',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
