# Generated by Django 3.2.6 on 2021-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TSW2', '0002_auto_20211018_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='locos',
            name='location',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
